### ISSUE TITLE
Problem when emulating on nexys

### ISSUE THREAD

**Issue by Clay-Cui** [openhwgroup/core-v-mcu#323]
Hi, I followed the readme file and try to use
`make nexys-emul` 
to generate the bitfile for the nexys board.
However, I keep getting this error
`ERROR: Setup failed : Cannot find emulation/core-v-mcu-nexys/rtl/core_v_mcu_nexys.v in .
cp ./build/openhwgroup.org_systems_core-v-mcu_0/nexys-a7-100t-vivado/openhwgroup.org_systems_core-v-mcu_0.runs/impl_1/core_v_mcu_nexys.bit emulation/core_v_mcu_nexys.bit
cp: cannot stat './build/openhwgroup.org_systems_core-v-mcu_0/nexys-a7-100t-vivado/openhwgroup.org_systems_core-v-mcu_0.runs/impl_1/core_v_mcu_nexys.bit': No such file or directory
Makefile:122: recipe for target 'nexys-emul' failed`

I looked into `./build/openhwgroup.org_systems_core-v-mcu_0/nexys-a7-100t-vivado/` there is only a subfolder called src, no folder is called run. How should I fix this?
And in the readme file, I don't quite get how to install latest board-parts with the core_v_nexys_200122.bit?

Thank you in advance for any help!

**Comment by Clay-Cui** [comment]
Thank you very much for your reply. 
I copied the file and found another error. 
`Traceback (most recent call last):
    assert loader is not None, "A loader was not found for the package."
AssertionError: A loader was not found for the package.`

Seems like an error regarding to the jinja2? I didn't change anything in the source code... Or does my environment is wrongly configured?

Thank you very much!

**Comment by MikeOpenHWGroup** [comment]
Glad to hear you've resolved the issue @Clay-Cui.  Would you be willing to contribute a pull-request to this repo to ensure the fix is available to everyone? Thanks!

**Comment by 124107157-KV** [comment]
Hi, I’d like to work on this issue. I confirmed that the filename mismatch is still present on the current `master`: the `nexys-emul` target generates `core_v_mcu_util.v`, while the FuseSoC Nexys fileset expects `core_v_mcu_nexys.v`. I’ll prepare a minimal Makefile-only fix and validate the Nexys build setup.

**Comment by MikeOpenHWGroup** [comment]
That's terrific @124107157-KV.  Please ensure you read [CONTRIBUTING](https://github.com/openhwgroup/core-v-mcu/blob/master/CONTRIBUTING.md#contributing).  A signed ECA is a "must have" for us.

**Comment by 124107157-KV** [comment]
Thanks Mike. I’ve read the contributing guidelines. I’ll has already signed the ECA and I will make sure that my Git commit email matches the ECA before opening the PR. I’ll proceed with the minimal Makefile fix for #323.
